#!/usr/bin/env bash
set -euo pipefail

MODE="${1:-https}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [ -f .env ]; then
  set -a
  . ./.env
  set +a
fi

DOMAIN="${DOMAIN:-supermario.o-r.kr}"
mkdir -p runtime nginx/conf.d

if [ ! -f runtime/active-colors.env ]; then
  cat > runtime/active-colors.env <<'EOF'
FRONTEND_ACTIVE=blue
BACKEND_ACTIVE=blue
LLM_ACTIVE=blue
EOF
fi

set -a
. runtime/active-colors.env
set +a

cat > nginx/conf.d/upstreams.conf <<'EOF'
# Generated by scripts/render-nginx.sh.
# Service colors are injected into app.conf as Docker DNS proxy variables.
EOF

case "$MODE" in
  http|https) ;;
  *)
    echo "Unsupported nginx mode: $MODE" >&2
    exit 1
    ;;
esac

TEMPLATE="nginx/conf.d/app.${MODE}.conf.template"
if [ ! -f "$TEMPLATE" ]; then
  echo "Missing nginx template: $TEMPLATE" >&2
  exit 1
fi

ESCAPED_DOMAIN="${DOMAIN//\//\\/}"
sed \
  -e "s/__DOMAIN__/${ESCAPED_DOMAIN}/g" \
  -e "s/__FRONTEND_ACTIVE__/${FRONTEND_ACTIVE:-blue}/g" \
  -e "s/__BACKEND_ACTIVE__/${BACKEND_ACTIVE:-blue}/g" \
  -e "s/__LLM_ACTIVE__/${LLM_ACTIVE:-blue}/g" \
  "$TEMPLATE" > nginx/conf.d/app.conf
echo "Rendered nginx ${MODE} config for ${DOMAIN}"
